baseURL = 'https://buda-base.github.io/blog/'
languageCode = 'en-us'
title = 'BDRC tech news'
#theme = ["PaperMod"]
theme = ["PaperMod"]

[params]
  description = "BDRC tech news"
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = true

[params.logo]
  image = "bdrc.svg"
  title = "BDRC Tech News"

# Logo configuration
[params.label]
  icon = "bdrc.svg"
  iconHeight = 40

[params.homeInfoParams]
  Title = 'Tibetan and Buddhist Tech Updates'
  Content = 'from the Buddhist Digital Resource Center'

[services]
  [services.googleAnalytics]
    id = 'G-FEE3EV1Y0R'

[params.widgets.social]
  cached = true # activate cache if true
  # Enable parts of social widget
  facebook = "BDRC.io"
  instagram = "buddhist_archive"
  github = "buda-base"
  email = "help@bdrc.io"

[params.sharingbuttons]
  facebook = true
  twitter = true
  email = true
